// Generated by scripts/gen-sw.mjs — do not edit by hand (npm run build).
// Cache-first shell: precache everything, serve from cache, fall back to network.
const CACHE = "sunrise-bb0d490fffb1";
const ASSETS = [
  "./",
  "manifest.webmanifest",
  "dist/sunrise.js",
  "data/packs/data-engineer.js",
  "data/packs/dev-roadmap.js",
  "themes/arcade-animated-v2.css",
  "themes/arcade-animated.css",
  "themes/arcade.css",
  "themes/aurora-noir.css",
  "themes/bauhaus.css",
  "themes/blueprint.css",
  "themes/bonus.css",
  "themes/dashboard.css",
  "themes/dawn.css",
  "themes/emerald.css",
  "themes/gazette.css",
  "themes/japanese.css",
  "themes/memphis.css",
  "themes/neon.css",
  "themes/os95.css",
  "themes/solarpunk.css",
  "themes/swiss.css",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(caches.match('./').then((r) => r ?? fetch(req)));
    return;
  }
  e.respondWith(caches.match(req, { ignoreSearch: true }).then((r) => r ?? fetch(req)));
});
