#!/usr/bin/env node
// Downloads the Google-Fonts families used by themes/*.css into fonts/ and emits
// fonts.css (an always-loaded @font-face sheet). Run manually when font usage
// changes — NOT part of `npm run build`, which must stay offline & deterministic.
// Outputs (fonts/, fonts.css) are committed like dist/ and sw.js.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';

const root = resolve(new URL('..', import.meta.url).pathname);
const KEEP = new Set(['latin', 'latin-ext', 'cyrillic']); // the app is EN/RU only
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

// 1. Collect every distinct Google Fonts @import URL across the themes.
const urls = new Set();
const themeDir = join(root, 'themes');
for (const f of readdirSync(themeDir).filter((f) => f.endsWith('.css'))) {
  const css = readFileSync(join(themeDir, f), 'utf8');
  const re = /@import\s+url\((['"]?)(https:\/\/fonts\.googleapis\.com\/[^'")]+)\1\)/g;
  let m;
  while ((m = re.exec(css))) urls.add(m[2]);
}

mkdirSync(join(root, 'fonts'), { recursive: true });
const faces = new Map(); // filename -> rewritten @font-face block (deduped)

for (const url of urls) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`fetch ${url} -> ${res.status}`);
  const css = await res.text();
  // Each face is preceded by a `/* subset */` comment.
  const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let b;
  while ((b = blockRe.exec(css))) {
    const subset = b[1];
    const block = b[2];
    if (!KEEP.has(subset)) continue;
    const fam = (/font-family:\s*'([^']+)'/.exec(block) || [])[1] || 'font';
    const wght = (/font-weight:\s*(\d+)/.exec(block) || [])[1] || '400';
    const style = /font-style:\s*italic/.test(block) ? 'italic' : 'normal';
    const src = (/src:\s*url\((https:\/\/[^)]+\.woff2)\)/.exec(block) || [])[1];
    if (!src) continue;
    const name = `${slug(fam)}-${wght}-${style}-${subset}.woff2`;
    if (faces.has(name)) continue;
    const bin = Buffer.from(
      await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer(),
    );
    writeFileSync(join(root, 'fonts', name), bin);
    faces.set(name, block.replace(src, `fonts/${name}`));
  }
}

const out =
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n` +
  `   Self-hosted @font-face for the bundled themes (offline; no remote deps). */\n` +
  `${[...faces.values()].join('\n')}\n`;
writeFileSync(join(root, 'fonts.css'), out);
console.log(`fonts.css: ${faces.size} faces from ${urls.size} imports`);
