#!/usr/bin/env node
// Generates sw.js: globs every shippable asset (a new theme/pack/icon can never
// be forgotten) and stamps a content-hash cache name (editing any asset busts
// the stale cache). sw.js is a committed build artifact like dist/sunrise.js;
// test/pwa/pwa-shell.test.ts fails if it goes stale.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const root = resolve(new URL('..', import.meta.url).pathname);
const list = (dir, ext) =>
  readdirSync(join(root, dir))
    .filter((f) => f.endsWith(ext))
    .sort()
    .map((f) => `${dir}/${f}`);

// The shell is cached as "./" — its canonical URL. Hosts with pretty URLs
// (Cloudflare Pages) 308-redirect /index.html to /, and a precached redirected
// response makes Chrome fail every SW-handled navigation with ERR_FAILED.
const ASSETS = [
  './',
  'manifest.webmanifest',
  'fonts.css',
  'dist/sunrise.js',
  ...list('data/packs', '.js'),
  ...list('themes', '.css'),
  ...list('fonts', '.woff2'),
  ...list('icons', '.png'),
];

const fileFor = (asset) => (asset === './' ? 'index.html' : asset);
const hash = createHash('sha256');
for (const a of ASSETS) hash.update(a).update(readFileSync(join(root, fileFor(a))));
const CACHE = `sunrise-${hash.digest('hex').slice(0, 12)}`;

const sw = `// Generated by scripts/gen-sw.mjs — do not edit by hand (npm run build).
// Cache-first shell: precache everything, serve from cache, fall back to network.
const CACHE = ${JSON.stringify(CACHE)};
const ASSETS = ${JSON.stringify(ASSETS, null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(caches.match('./').then((r) => r ?? fetch(req)));
    return;
  }
  e.respondWith(caches.match(req, { ignoreSearch: true }).then((r) => r ?? fetch(req)));
});
`;

writeFileSync(process.argv[2] ?? join(root, 'sw.js'), sw);
console.log(`sw.js: ${ASSETS.length} assets, cache ${CACHE}`);
